RazorAreas/RazorAreas/Pages/Admin/Index.cshtml.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using RazorAreas.Areas.Identity.Data.DbContexts;

namespace RazorAreas.Pages.Admin
{
    public class AdminPageModel : PageModel
    {
        private readonly UserContext _context;

        public AdminPageModel(UserContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetEditUser(string id)
        {
            return RedirectToPage("Manage/EditUser", new {id = id});
        }
        
        public async Task<IActionResult> OnGetDeleteUser(string id)
        {
            Console.WriteLine("Delete");
            return RedirectToPage("Index");

        }
        
        public async Task<IActionResult> OnGetGrantUser(string id)
        {
            Console.WriteLine("Grant");
            return RedirectToPage("Index");
        }
        
    }
}

RazorAreas/RazorAreas/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorAreas.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

RazorAreas/RazorAreas/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorAreas.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorAreas/RazorAreas/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorAreas.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

RazorAreas/RazorAreas/Pages/Admin/AdminPage.cshtml
@page


@using Microsoft.AspNetCore.Identity
@using RazorAreas.Areas.Identity.Data.DbContexts
@using RazorAreas.Areas.Identity.Data.Models
@inject UserManager<AppUser> userManager;
@inject UserContext context;

@model RazorAreas.Pages.Admin.AdminPageModel
@{
}

<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Email</th>
            <th>Действия</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var user in context.Users.ToList())
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <a class="btn btn-primary">Изменить</a>
                    <a class="btn btn-danger">Удалить</a>
                    <a class="btn btn-warning">Изменить права</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RazorAreas/RazorAreas/Pages/Admin/Index.cshtml
@page


@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> userManager;


@model RazorAreas.Pages.Admin.AdminPageModel


<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Email</th>
            <th>Действия</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var user in userManager.Users)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <a asp-page-handler="EditUser" asp-route-id="@user.Id" class="btn btn-primary">Изменить</a>
                    <a asp-page-handler="DeleteUser" asp-route-id="@user.Id" class="btn btn-danger">Удалить</a>
                    <a asp-page-handler="GrantUser" asp-route-id="@user.Id" class="btn btn-warning">Изменить права</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RazorAreas/RazorAreas/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}-

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorAreas/RazorAreas/Pages/Shared/_AdminLayout.cshtml
@using RazorAreas.Areas.Identity.Data.Models;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorAreas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RazorAreas.styles.css" asp-append-version="true"/>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">RazorAreas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-page="/Admin/Index">Admin menu</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Logout">Log Out</a>
                    </li>
                    }
                    else
                    {
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Sign up</a>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted mt-3 py-3">
    <div class="container text-center">
        &copy; 2024 - RazorAreas - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>

</html>

RazorAreas/RazorAreas/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorAreas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorAreas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorAreas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RazorAreas - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RazorAreas/RazorAreas/Pages/Shared/_UserLayout.cshtml
@using RazorAreas.Areas.Identity.Data.Models;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorAreas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RazorAreas.styles.css" asp-append-version="true"/>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">RazorAreas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Order Food</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                  <partial name="_LoginPartial"/>
                </ul>
            </div>
        </div>
    </nav>




</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted mt-3 py-3">
    <div class="container text-center">
        &copy; 2024 - RazorAreas - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>

</html>